# Generated by Django 3.2 on 2022-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adderss',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Dr. Notes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Treatment'),
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Visit Date'),
        ),
    ]
